Settings:
  Repeater:
    # If enabled then any non-player entity will be pushed along a (powered) repeater path.
    Enabled: true

    # If enabled then non-player entities on top of a fast block will move faster
    FastEnabled: true

    # Normal multiplier
    Normal: 1.5

    # Fast block multiplier
    Fast: 3.0

    # Fast block id. By default IRON_BLOCK
    FastBlock: IRON_BLOCK

  StairCannon:
    # WOOD STAIR RAILGUN/CANNON(s) 
    Enabled: true

    # The force multiplier
    Force: 1.5

  StairCannon2:
    # NETHER BRICK STAIR RAILGUN/CANNON(s)
    Enabled: true

    # The force multiplier
    Force: 1.5

  StairCannon3:
    # QUARTZ STAIR RAILGUN/CANNONS(s)
    Enabled: true

    # The force multiplier
    Force: 2.0

    # The minimum amount of TPS when the plugin should run
    MinimumTPS: 7.5
